---
root: 
permalink: /blog/:year/:month/:day/:title
lsi: false
pygments: true

#
# Site configuration
#
url:          http://sdk.gooddata.com
title:        GoodData SDK Site
description:  Updates on the GoodData tools and APIs ecosystem
keywords:     gooddata, good, data, blog, bi, analytics, gdcl, cl, integration, upload, analyze
author:       Good Data
email:        support@gooddata.com
